FROM centos:latest

ENV JAVA_HOME=/usr/local/jdk1.8.0_201
ENV TOMCAT_HOME=/home/tomcat/apache-tomcat-8.5.32
ENV PATH=$JAVA_HOME/bin:$TOMCAT_HOME/bin:$PATH
RUN useradd -d /home/tomcat -s /usr/sbin/nologin tomcat \
    && gpasswd -a tomcat tomcat \
    && chown -R tomcat:tomcat /home/tomcat

ADD jdk-8u201-linux-x64.tar.gz /usr/local
ADD apache-tomcat-8.5.32.tar.gz /home/tomcat

ENTRYPOINT ["catalina.sh","run"]
